all:
  hosts:
    main:
      ansible_host: 52.149.211.202
      ip: 10.0.1.9
      access_ip: 52.149.211.202
    one:
      ansible_host: 52.149.213.76
      ip: 10.0.1.6
      access_ip: 52.149.213.76
    two:
      ansible_host: 52.149.211.196
      ip: 10.0.1.4
      access_ip: 52.149.211.196
    xxx4:
      ansible_host: 52.146.33.17
      ip: 10.0.1.8
      access_ip: 52.146.33.17
    xxx6:
      ansible_host: 52.149.213.68
      ip: 10.0.1.5
      access_ip: 52.149.213.68
    xxx7:
      ansible_host: 52.188.172.238
      ip: 10.0.1.7
      access_ip: 52.188.172.238
  children:
    kube-master:
      hosts:
        main:
    kube-node:
      hosts:
        main:
        one:
        two:
        xxx4:
        xxx6:
        xxx7:
    etcd:
      hosts:
        main:
        one:
        two:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
