all:
  hosts:
    main:
      ansible_host: 137.135.71.135
      ip: 10.0.1.7
      access_ip: 137.135.71.135
    one:
      ansible_host: 137.135.64.151
      ip: 10.0.1.4
      access_ip: 137.135.64.151
    two:
      ansible_host: 137.135.64.92
      ip: 10.0.1.8
      access_ip: 137.135.64.92
    xxx4:
      ansible_host: 137.135.64.227
      ip: 10.0.1.6
      access_ip: 137.135.64.227
    xxx6:
      ansible_host: 137.135.65.37
      ip: 10.0.1.9
      access_ip: 137.135.65.37
  children:
    kube-master:
      hosts:
        main:
    kube-node:
      hosts:
        main:
        one:
        two:
        xxx4:
        xxx6:
    etcd:
      hosts:
        main:
        one:
        two:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
