all:
  hosts:
    main:
      ansible_host: 13.92.27.105
      ip: 10.0.1.5
      access_ip: 13.92.27.105
    one:
      ansible_host: 52.234.178.27
      ip: 10.0.1.9
      access_ip: 52.234.178.27
    two:
      ansible_host: 52.234.178.25
      ip: 10.0.1.8
      access_ip: 52.234.178.25
    xxx4:
      ansible_host: 13.68.189.171
      ip: 10.0.1.4
      access_ip: 13.68.189.171
    xxx6:
      ansible_host: 13.92.31.214
      ip: 10.0.1.6
      access_ip: 13.92.31.214
  children:
    kube-master:
      hosts:
        main:
    kube-node:
      hosts:
        main:
        one:
        two:
        xxx4:
        xxx6:
    etcd:
      hosts:
        main:
        one:
        two:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
