all:
  hosts:
    node1:
      ansible_host: 34.75.56.94
      ip: 10.142.0.26
      access_ip: 34.75.56.94
    node2:
      ansible_host: 104.196.213.46
      ip: 10.142.0.30
      access_ip: 104.196.213.46
    node3:
      ansible_host: 34.73.18.242
      ip: 10.142.0.27
      access_ip: 34.73.18.242
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
