all:
  hosts:
    main:
      ansible_host: 40.114.118.34
      ip: 10.0.1.6
      access_ip: 40.114.118.34
    one:
      ansible_host: 40.88.124.183
      ip: 10.0.1.5
      access_ip: 40.88.124.183
    two:
      ansible_host: 13.92.100.65
      ip: 10.0.1.4
      access_ip: 13.92.100.65
  children:
    kube-master:
      hosts:
        main:
    kube-node:
      hosts:
        main:
        one:
        two:
    etcd:
      hosts:
        main:
        one:
        two:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
